const words = [
    "HELLO", "WORLD", "APPLE", "CHAIR", "TABLE", "HOUSE", "MOUSE", "HORSE", "CLOUD", "TRAIN",
    "BRICK", "CRISP", "SHINE", "PLANE", "GLASS", "FROST", "STORM", "MUSIC", "SWEET", "QUICK",
    "FLOOR", "BRAVE", "HEART", "TRICK", "SKILL", "SOUND", "GLOWN", "FRESH", "GRASS", "SHORE",
    "PLATE", "CLOCK", "BRUSH", "BRAND", "STICK", "TREND", "GUESS", "BLANK", "CRASH", "FLAKE",
    "SMILE", "SHAPE", "SHIRT", "CROSS", "PRIZE", "PULSE", "BLOCK", "STAND", "STUFF", "SHIFT",
    "CHAIN", "LIGHT", "SCENE", "VOICE", "STORY", "WINDY", "YOUTH", "WATER", "LEVEL", "TRACK",
    "CROWN", "DREAM", "PRIDE", "SPACE", "DRESS", "SHIFT", "GLIDE", "PRIME", "STAGE", "LARGE",
    "SMALL", "THING", "EXACT", "BRISK", "FLARE", "STONE", "CRANE", "TRUST", "BLEND", "GRADE",
    "BLAST", "TREAD", "GRANT", "CRAFT", "FINAL", "SLEEP", "STEEP", "TRAIL", "BLINK", "CREST",
    "DRIFT", "LEMON", "BRISK", "PRIOR", "FRONT", "DRIVE", "WHEEL", "CRISP", "SMART", "CLEAR",
    "CRISP", "GROVE", "PAINT", "GRIND", "FRAME", "DRINK", "SLICE", "PRUNE", "LAYER", "BLOCK",
    "SHIFT", "BRISK", "FLOOD", "BRAVE", "SHINE", "DRILL", "CREEK", "BLANK", "GRACE", "STONE",
    "FRANK", "BLANK", "PRIZE", "SCALE", "STARE", "GHOST", "CLEAR", "TIGHT", "BLAST", "GRAPE",
    "CRANE", "FROWN", "SWING", "PITCH", "STAND", "CHAIN", "SLEEP", "PRIME", "GRANT", "SHADE",
    "WORTH", "SHINE", "PLATE", "SHEAR", "CRACK", "BLEND", "DRIVE", "SHOCK", "FRONT", "SHADE"
];
export default words;